<a href="https://colab.research.google.com/github/yrhutu21/NLP/blob/main/Casual_Mask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np
import torch

In [2]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
np.tril(np.ones((4,4)))

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [4]:

def causal_mask(seq_len):
    return torch.tril(torch.ones((seq_len, seq_len))).bool()

In [5]:
causal_mask(4)

tensor([[ True, False, False, False],
        [ True,  True, False, False],
        [ True,  True,  True, False],
        [ True,  True,  True,  True]])

In [6]:
np.tril(np.ones((4,4)))

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [7]:
# scores = scores.masked_fill(causal_mask == 0, float('-inf'))

In [8]:
Q = torch.randn(1, 4, 8)  # (batch=1, seq_len=4, d_k=8)
K = torch.randn(1, 4, 8)

In [9]:

K.shape

torch.Size([1, 4, 8])

In [10]:

K.transpose(-2, -1).shape

torch.Size([1, 8, 4])

In [11]:

scores = Q @ K.transpose(-2, -1)

In [12]:

scores

tensor([[[-4.8263,  0.0533,  0.4051,  0.9552],
         [-1.6908, -4.7683, -3.0699,  4.9278],
         [-2.3103, -1.7604, -0.1232,  1.1981],
         [-3.6772,  2.1976,  1.4153,  1.5783]]])

In [13]:
scores.shape

torch.Size([1, 4, 4])

In [15]:

mask = torch.tril(torch.ones(4, 4))

In [16]:
mask

tensor([[1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])

In [17]:
scores = scores.masked_fill(mask == 0, float('-inf'))

In [18]:

scores

tensor([[[-4.8263,    -inf,    -inf,    -inf],
         [-1.6908, -4.7683,    -inf,    -inf],
         [-2.3103, -1.7604, -0.1232,    -inf],
         [-3.6772,  2.1976,  1.4153,  1.5783]]])

In [19]:

attn = torch.softmax(scores, dim=-1)

In [20]:
attn

tensor([[[1.0000, 0.0000, 0.0000, 0.0000],
         [0.9560, 0.0440, 0.0000, 0.0000],
         [0.0859, 0.1489, 0.7653, 0.0000],
         [0.0014, 0.5004, 0.2288, 0.2694]]])

In [21]:
import torch

In [22]:

A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [23]:
mask = torch.full((3,3), float('-inf'))

In [24]:
mask

tensor([[-inf, -inf, -inf],
        [-inf, -inf, -inf],
        [-inf, -inf, -inf]])

In [25]:
torch.tril(A)

tensor([[1, 0, 0],
        [4, 5, 0],
        [7, 8, 9]])

In [26]:
torch.tril(A, diagonal=-1)

tensor([[0, 0, 0],
        [4, 0, 0],
        [7, 8, 0]])

In [27]:

torch.triu(A)

tensor([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9]])

In [28]:
torch.triu(A, diagonal=-1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [0, 8, 9]])